# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "Premios de Datos Abiertos de Madrid 2017"
email: "visualizar@medialab-prado.es"
description: "En colaboración con Medialab-Prado y el Laboratorio de Datos DataLab, el Ayuntamiento de Madrid lanza la segunda convocatoria de los concursos de Periodismo de Datos y Datatón Ciudad de Madrid con el objetivo de fomentar el uso de la información del sector público del Portal de Datos Abiertos"
baseurl: "/datamad2017"
url: "https://medialab-prado.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-107707479-1"
googleAnalyticsSiteUrl: "medialab-prado.github.io"
siteVerification: ""

# Organizer Info
organizerName: "Datalabx"
organizerAlternateName: "Medialab-prado"
organizerDescription: "Data Laboratory at Medialab-Prado."
organizerEmail: "visualizar@medialab-prado.es"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://medialab-prado/visualizar"

# Head
metaKeywords: "event, datos abiertos, datatón, madrid, periodismo de datos, visualización, medialab-prado, datalab"
twitterAccount: "@datalabx"
socialImageSrcGooglePlus: "/img/seo/dataton_seo.png?20171104"
socialImageSrcTwitter: "/img/seo/dataton_seo.png?20171104"
socialImageSrcFacebook: "/img/seo/dataton_seo.png?20171104"

# Documents
c4pUrl: "http://medialab-prado.es/article/premio-dataton-ciudad-de-madrid-2017"
#c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Inicio"}
 - {permalink: "/programa/", text: "Programa"}
 - {permalink: "/ponentes/", text: "Ponentes"}
 - {permalink: "/proyectos", text: "Proyectos"}
 - {permalink: "/articulos/", text: "Artículos"}
 - {permalink: "/jurado/", text: "Jurado"}
 - {permalink: "/equipo/", text: "Equipo"}

# Home Block
homeImage: "home.jpg"
# Hero Block
heroTitle: "DataMad <typeout>2017"
eventDate: "16 Diciembre - Entrega de Premios"
typeoutTextValues: '"", "", "Periodismo de datos", "Datatón"'
typeoutFallback: "Datatón Ciudad de Madrid"

# About Block
aboutTitle: "Acerca del DataMad"
aboutDescription: "En colaboración con Medialab Prado y el Laboratorio de Datos DataLab, el Ayuntamiento de Madrid lanza la <a href='http://medialab-prado.es/article/datamad'>segunda convocatoria de los concursos de Periodismo de Datos y Datatón Ciudad de Madrid</a> con el objetivo de fomentar el uso de la información del sector público del <a href='http://datos.madrid.es/portal/site/egob/'>Portal de Datos Abiertos</a> y del <a href='http://transparencia.madrid.es/'> Portal de Transparencia</a>."
aboutBlock:
 - {title: "Ponencias", image: "acerca-ponencias.jpg", text: "Representantes de organismos públicos nos hablarán de sus datos y servicios abiertos" }
 - {title: "Datatón Ciudad de Madrid 2017", image: "acerca-dataton.jpg", text: "Ideas y proyectos originales o evolutivos basados, al menos en una parte significativa, en los datos del Ayuntamiento de Madrid, bien del <a href='http://datos.madrid.es/portal/site/egob/'>Portal de Datos Abiertos</a> o del <a href='http://transparencia.madrid.es/'> Portal de Transparencia</a> de Madrid." }
 - {title: "Premio Periodismo de Datos", image: "acerca-periodismo.jpg", text: "Celebramos el <a href='http://medialab-prado.es/article/premio-periodismo-de-datos-ciudad-de-madrid-2017'>Premio de Periodismo de Datos</a> para piezas periodísticas que usen datos del <a href='http://datos.madrid.es/portal/site/egob/'>Portal de Datos Abiertos</a> y/o del <a href='http://transparencia.madrid.es/'> Portal de Transparencia</a> de Madrid, hasta el 31 de octubre" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "60", specialCharacter: "+", info: "asistentes", detail: "de diferentes perfiles"}
 - {count: "48", specialCharacter: "+", info: "horas", detail: "de trabajo con datos abiertos"}
 - {count: "4", specialCharacter: "+", info: "ponentes", detail: "de organismos públicos de la ciudad"}
 - {count: "2", specialCharacter: "", info: "modalidades", detail: "una para profesionales y otra para estudiantes de cualquier disciplina"}

# Latest News Block
latestNewsTitle: "Últimas noticias"

# Rockstar Speakers Block
rockstarSpeakersImage: "ponentes.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Expertos en datos abiertos"
rockstarSpeakersButtonText: "Ver todos los ponentes"
rockstarSpeakersButtonLink: "/ponentes/"

# Location Block
locationBlockImage: "mapa-medialab-prado.png"

locationBlockTitle: "Lugar"
eventLocationName: "Medialab-Prado"
eventLocationLink: "http://medialab-prado.es"
eventStreetAddress: "Plaza de las Letras. Calle Alameda, 15 "
eventAddressLocality: "Madrid"
eventAddressLocalityRegion: "Madrid"
eventPostalCode: "28014"
eventAddressCountry: "Spain"
eventStartTime: "2017-10-20T10:00"
eventDoorTime: "09:00"
eventEndTime: "2017-10-22T20:00"
eventPlaceCoordinates: "40.41063,-3.69366"
mapCenterCoordinates: "40.41063,-3.69366"
mapMobileCenterCoordinates: "40.4108497,-3.6938703"

# Venue Block
venueBlockTitle: "Instalaciones"
venueBigImage: "instalaciones-grande.jpg"
venueSmallImage1: "instalaciones-1.jpg"
venueSmallImage2: "instalaciones-2.jpg"
venueSmallImage3: "instalaciones-3.jpg"
venueTitle: "Medialab-Prado"
venueFeatures: ["Medialab-Prado es un laboratorio ciudadano de producción, investigación y difusión de proyectos culturales"]

# Partners Block
organizersTitle: "Organiza"
partnersTitle: ""

# Tickets Block
ticketsTitle: "Inscripciones"
ticketsInfo: "El fallo de los premios se dará a conocer el viernes 15 de diciembre"
ticketsOffers:
 -
  name: "Convocatoria de proyectos"
  price: "13"
  priceCurrency: "proyectos"
  ticketsNumber: ""
  buyButtonLink: ""
  buyButtonText: "Buy Now"
  ticketContentList: ["Datos Abiertos", "Software Libre"]
  validFrom: "2017-08-25T10:00"
  validThrough: "2017-09-30T23:59"
  soldOut: true
  soldOutText: "Plazo finalizado"
 -
  name: "Convocatoria de colaboradores"
  price: "60"
  priceCurrency: "colaboradores"
  ticketsNumber: "100"
  featured: true
  buyButtonLink: "http://medialab-prado.es/article/premio-dataton-ciudad-de-madrid-2017"
  buyButtonText: "Apúntate ahora"
  ticketContentList: ["Todos los perfiles bienvenidos", "investigadores, artistas, curiosos..."]
  validFrom: "2017-10-09T00:00"
  validThrough: "2017-10-19T23:59"
  disabled: true

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=DataLabx", icon: "twitter"}
 - {link: "https://es-es.facebook.com/MedialabPradoMadrid", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Enlaces"
  links:
   - {link: "http://medialab-prado.es", text: "Medialab-Prado"}
   - {link: "http://datos.madrid.es/portal/site/egob/", text: "Portal de datos abiertos del Ayuntamiento de Madrid"}
 -
  title: "Contacto"
  links:
   - {link: "mailto:visualizar@medialab-prado.es", text: "visualizar@medialab-prado.es"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Código de Conducta"}

# Blog
blogTitle: "Últimas entradas"
blogCommentsEnabled: true
discusShortName: "datamad17"

# Speakers List Block
showSessions: true

# Team Block
aboutUs: ""

# Proyectos
hackathonTitle: "Proyectos"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Proyectos seleccionados"
hackathonRows:

# Hackathon Prizes Block
prizesTitle: "Premios"
prizes:
 - {title: "Segundo Premio", image: "prize-2.png", info: "1.000 €"}
 - {title: "Primer Premio", image: "prize-1.png", info: "2.500 €"}
 - {title: "Tercer Premio", image: "prize-3.png", info: "500 €"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Medialab-Prado"
hackathonLocationLink: "http://medialab-prado.es"
hackathonStreetAddress: "Plaza de las Letras. Calle Alameda,15"
hackathonAddressLocality: "Madrid"
hackathonAddressLocalityRegion: "Madrid"
hackathonPostalCode: "28014"
hackathonAddressCountry: "Spain"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2017-10-20T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2017-10-22T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "40.41063, -3.69366"
hackathonMapCenterCoordinates: "40.41063,-3.69366"
hackathonMapMobileCenterCoordinates: "40.41063,-3.69366"
